version: '3.8'

services:
    generator:
        container_name: generator
        build:
            dockerfile: Dockerfile
            context: .
        volumes:
            - ./:/app/
            - /app/node_modules
        restart: always
        command: tail -f /dev/null
